name: project_submission

on:
  workflow_dispatch:
  pull_request:
    paths:
      - projects/tt_um_*/**

jobs:
  check_submission:
    name: Check user module submission
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r tt-multiplexer/py/requirements.txt -r tt/requirements.txt

      # Install yosys (required for tt/configure.py)
      - name: install oss-cad-suite
        uses: YosysHQ/setup-oss-cad-suite@v2
        with:
          version: '2023-05-27'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update caravel configuration
        run: python ./tt/configure.py --update-caravel

      - name: upload mux_index.json
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: mux_index
          path: mux_index.json
